MotChallenge2DBox
test_tracker
Traceback (most recent call last):
  File "D:\Documents\Master of CV\DL in CV\TrackEval\trackeval\eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "D:\Documents\Master of CV\DL in CV\TrackEval\trackeval\_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "D:\Documents\Master of CV\DL in CV\TrackEval\trackeval\eval.py", line 195, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "D:\Documents\Master of CV\DL in CV\TrackEval\trackeval\_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "D:\Documents\Master of CV\DL in CV\TrackEval\trackeval\datasets\mot_challenge_2d_box.py", line 366, in get_preprocessed_seq_data
    raise(TrackEvalException('Attempting to evaluate using invalid gt classes. '
trackeval.utils.TrackEvalException: Attempting to evaluate using invalid gt classes. This warning only triggers if preprocessing is performed, e.g. not for MOT15 or where prepropressing is explicitly disabled. Please either check your gt data, or disable preprocessing. The following invalid classes were found in timestep 0: -1





MotChallenge2DBox
test_tracker
Traceback (most recent call last):
  File "D:\Documents\Master of CV\DL in CV\TrackEval\trackeval\eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "D:\Documents\Master of CV\DL in CV\TrackEval\trackeval\_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "D:\Documents\Master of CV\DL in CV\TrackEval\trackeval\eval.py", line 195, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "D:\Documents\Master of CV\DL in CV\TrackEval\trackeval\_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "D:\Documents\Master of CV\DL in CV\TrackEval\trackeval\datasets\mot_challenge_2d_box.py", line 368, in get_preprocessed_seq_data
    raise(TrackEvalException('Attempting to evaluate using invalid gt classes. '
trackeval.utils.TrackEvalException: Attempting to evaluate using invalid gt classes. This warning only triggers if preprocessing is performed, e.g. not for MOT15 or where prepropressing is explicitly disabled. Please either check your gt data, or disable preprocessing. The following invalid classes were found in timestep 0: -1





MotChallenge2DBox
test_tracker
Traceback (most recent call last):
  File "D:\Documents\Master of CV\DL in CV\evaluation\trackeval\eval.py", line 153, in evaluate
    metric.plot_single_tracker_results(table_res, tracker_display_name, c_cls,
  File "D:\Documents\Master of CV\DL in CV\evaluation\trackeval\metrics\hota.py", line 185, in plot_single_tracker_results
    from matplotlib import pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'





